name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-2022

          - name: Android32
            os: ubuntu-22.04
            target: Android32

          - name: Android64
            os: ubuntu-22.04
            target: Android64

          - name: macOS
            os: macos-14

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install Geode Binaries
        run: |
          geode sdk install-binaries || true

      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
          combine: true

      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
          combine: true

  package:
    name: Package Mod (.geode)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Package Multi-platform Mod
        uses: geode-sdk/build-geode-mod/combine@main
        with:
          output: "DashChat.geode"

      - name: Upload Mod Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DashChat-Geode-Mod
          path: DashChat.geode