name: Build Geode Mod

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          - name: macOS
            os: macos-latest

    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Geode SDK
        uses: geode-sdk/setup-geode-action@v1
        with:
          sdk: nightly

      # Chạy build mod
      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true